/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBook: typeof import('./components/AddBook.vue')['default']
    AddWorkout: typeof import('./components/AddWorkout.vue')['default']
    BaseSeparator: typeof import('./components/BaseSeparator.vue')['default']
    copy: typeof import('./components/ManageLibraries copy.vue')['default']
    ManageLibraries: typeof import('./components/ManageLibraries.vue')['default']
    OverviewData: typeof import('./components/OverviewData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./components/SettingsMenu.vue')['default']
    TopToolbar: typeof import('./components/TopToolbar.vue')['default']
  }
}
