/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBook: typeof import('./components/AddBook.vue')['default']
    BaseSeparator: typeof import('./components/BaseSeparator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./components/SettingsMenu.vue')['default']
    TopToolbar: typeof import('./components/TopToolbar.vue')['default']
  }
}
